# Generated by Django 3.2.4 on 2021-06-29 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=128)),
                ('plate', models.CharField(max_length=8)),
                ('bus_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('marker_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('title', models.CharField(max_length=128)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('birth_date', models.DateTimeField()),
                ('cpf', models.CharField(max_length=14)),
                ('driver_license_type', models.CharField(max_length=1)),
                ('civil_state', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('inspector_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('route_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('route_stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.busstop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.route')),
            ],
        ),
        migrations.CreateModel(
            name='InspectorStop',
            fields=[
                ('inspector_stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.busstop')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.inspector')),
            ],
        ),
    ]
